version: '3'

services:
    compile:
        build: .
        volumes:
            - "./bin:/src"
        command: cobc -x ./program.cbl ; ./program
    run:
        build: .
        volumes:
            - "./bin:/src"
        command: ./program
        depends_on: 
            - db
    db:
        image: postgres
        env_file:
            - database.env
        environment: 
            - PGPASSWORD:password
        volumes: 
            - "./data:/ingest"
            - "./src/postgres:/sql"
        #logging:
            #driver: none